### ISSUE TITLE
Internal error, Apache, Redmine 1.1.1

### ISSUE THREAD

**Issue by msorc** [SphereSoftware/easy_agile#12]
In installed your easy_agile plugin in newest redmine but am receiving the following error.
When I remove the easy_agile folder again and do another rake db:migrate_plugins RAILS_ENV=production

and restert Apache than it is working again but without easy_agile Plugin.

How can I now get your plugin working in 1.1.1

I hope you can help me

Andi

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your redMine administrator for assistance.

**Comment by msorc** [comment]
Please provide your production.log

Make sure you have done all steps mentioned in Install section (i.e. installed all required gems and plugins).

Thanks.

**Comment by a-c-m** [comment]
I've not yet installed this, but on http://www.redmine.org/plugins/easy_agile it reports 1.0 support only. Can any of the dev's confirm they have it working on 1.1 ?

Thanks.

**Comment by msorc** [comment]
It should work
