### ISSUE TITLE
Users receive an Internal Error on "My Page"

### ISSUE THREAD

**Issue by rileyw** [SphereSoftware/easy_agile#17]
Users are adding the "Active Work" page block to their "My Page" and as soon the page block has been added an "Internal Error" is returned. The production.log reports the following:

<pre><code>
ActionView::TemplateError (undefined method `pending?' for nil:NilClass) on line #11 of vendor/plugins/easy_agile/app/views/my/blocks/_active_work.erb:
8: &lt;li class="&lt;%= cycle('odd', 'even') %&gt;"&gt;
9:   &lt;div class="iteration"&gt;
10:     &lt;%= link_to(
11:       image_tag(iteration.pending? ? 'burndown.png' : project_iteration_burndown_path(iteration.project, iteration, :width =&gt; width),
12:         :width =&gt; width, :height =&gt; height, :alt =&gt; "Burndown chart for #{h iteration.name}"),
13:       [iteration.project, iteration]) %&gt;
14:     &lt;%= link_to h(iteration), [iteration.project, iteration] %&gt;

    vendor/plugins/easy_agile/app/views/my/blocks/_active_work.erb:11
    app/views/my/page.rhtml:11:in `_run_rhtml_app47views47my47page46rhtml'
    app/views/my/page.rhtml:8:in `each'
    app/views/my/page.rhtml:8:in `_run_rhtml_app47views47my47page46rhtml'
    dispatch.fcgi:24
</code></pre>

**Comment by patakijv** [comment]
Getting this also - how to resolve or undo adding the block to My Page?

**Comment by rileyw** [comment]
You will need to edit the user_preferences table, find the row for the appropriate user_id, and remove the "active_work" line from the row contents. I forget the exact column name.

**Comment by rileyw** [comment]
Ack -- Didn't mean to close.

**Comment by rnuno** [comment]
I'm also seeing this error.  Anyway on how to fix it?

To clean it you need to:
1) Open user_preferences table
2) locate your user_id
3) delete -active_work from the "others" field.

**Comment by msorc** [comment]
Fixed
