### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by jmorata** [SphereSoftware/easy_agile#20]
Hi,
I've installed easy_agile following instructions, but when restarting redmine and clicking on easy agile tab; server sends internal error:

Processing EasyAgileController#show (for 192.168.23.67 at 2011-03-31 12:10:52) [GET]
  Parameters: {"project_id"=>"gex", "action"=>"show", "controller"=>"easy_agile"}
Rendering template within layouts/ea_base
Rendering easy_agile/show_guidance

ActionView::TemplateError (undefined method `inside_layout' for #ActionView::Base:0xb5b5a080) on line #1 of vendor/plugins/easy_agile/app/views/layouts/ea_base.html.erb:
1: <% inside_layout 'base' do -%>
2: <% content_for :header_tags do %>
3: <%= stylesheet_link_tag(
4:                         'story/layout',

```
vendor/plugins/easy_agile/app/views/layouts/ea_base.html.erb:1
vendor/plugins/easy_agile/app/controllers/easy_agile_controller.rb:8:in `show'
```

Rendering /opt/bitnami/apps/redmine/public/500.html (500 Internal Server Error)

Can you help me ?
THX

**Comment by jmorata** [comment]
Redmine 1.0.4.stable (MySQL)

**Comment by msorc** [comment]
Please make sure you installed all the required gems and plugins (see README). Especially nested_layouts

**Comment by jmorata** [comment]
Thank you,

I missed install nested_layouts.

2011/3/31 msorc <
reply@reply.github.com>

**Comment by msorc** [comment]
ok
