### ISSUE TITLE
не работает переименование проекта при подключенном easy_agile

### ISSUE THREAD

**Issue by evgeniypl** [SphereSoftware/easy_agile#4]
не работает переименование проекта при подключенном easy_agile  - отключаешь плагин все корректно работает 
версия Redmine 1.0.3.stable ? модуль последний с github 
последовательность действий  подключчаем модуль , проект , настройка проекта , информация , меняем имя проекта  нажимаем сохранить  -  выдает 404 
при отключеном модуле все ок

**Comment by msorc** [comment]
спасибо, будет рассмотрено в ближайшие дни
