### ISSUE TITLE
missing Redmine observers

### ISSUE THREAD

**Issue by mateuszdraco** [SphereSoftware/easy_agile#8]
Current version have serious issue - it overwrite default observers. Very annoying bug that cause ie mails are not being sent. I've spent several long hours debugging Redmine and trying to figure out why my Redmine stopped sending emails.

You can change it for example like this:
ActiveRecord::Base.observers << :acceptance_criterion_observer << :story_action_observer

**Comment by msorc** [comment]
https://github.com/SphereConsultingInc/easy_agile/commit/279aa5f861ab545c001efe6889c9b8e7e8b854a5
