### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by kopra** [SphereSoftware/easy_agile#9]
Got error 500 when click on easy agile tab, log:

ActionView::TemplateError (undefined method `inside_layout' for
# ActionView::Base:0xf614f810) on line #1 of

vendor/plugins/easy_agile/app/views/layou[1~ts/ea_base.html.erb:
1: <% inside_layout 'base' do -%>
2: <% content_for :header_tags do %>
3: <%= stylesheet_link_tag(
4:                         'story/layout',

```
vendor/plugins/easy_agile/app/views/layouts/ea_base.html.erb:1
vendor/plugins/easy_agile/app/controllers/easy_agile_controller.rb:8:in `show'
```

Rendering /usr/local/redmine/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by msorc** [comment]
what is your redmine version?
what other plugins do you have?

**Comment by kopra** [comment]
1.0.4 with bitnami stack and we are using "Redmine Close Button plugin" and "Redmine Doodles plugin"

**Comment by msorc** [comment]
Have you installed  nested_layouts plugin (see README)?

**Comment by kopra** [comment]
Nope, ups, thanks for your help. Problem solved!
